export enum ServiceUsageType {
  USER = 'USER',
  STORE = 'STORE',
  ITEM = 'ITEM',
  PRODUCT = 'PRODUCT',
  PRODUCT_AUTOMATOR = 'PRODUCT_AUTOMATOR',
  NOTIFICATION = 'NOTIFICATION',
  NOTIFICATION_SMS = 'NOTIFICATION_SMS',
  NOTIFICATION_LMS = 'NOTIFICATION_LMS',
  NOTIFICATION_MMS = 'NOTIFICATION_MMS',
  NOTIFICATION_EMAIL = 'NOTIFICATION_EMAIL',
  NOTIFICATION_TEMPLATE = 'NOTIFICATION_TEMPLATE',
  PURCHASE = 'PURCHASE',
  SETTLEMENT = 'SETTLEMENT',
  SETTLEMENT_MALL = 'SETTLEMENT_MALL',
  FILE = 'FILE',
  USER_BUSINESS = 'USER_BUSINESS',
  USER_CUSTOMER = 'USER_CUSTOMER',
}

export enum Action {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
}

export enum DisplayType {
  DROPDOWN = 'DROPDOWN',
  TIME_PICKER = 'TIME_PICKER',
  TEXT_INPUT = 'TEXT_INPUT',
  NUMBER_SELECTOR = 'NUMBER_SELECTOR',
  CHECK_BOX = 'CHECK_BOX',
  RADIO_BOX = 'RADIO_BOX',
  DATE_PICKER = 'DATE_PICKER',
  DATE_RANGE_PICKER = 'DATE_RANGE_PICKER',
  DATETIME_PICKER = 'DATETIME_PICKER',
  DATETIME_RANGE_PICKER = 'DATETIME_RANGE_PICKER',
}

export enum ProductType {
  NORMAL = 'NORMAL',
  BOOKING = 'BOOKING',
}

export enum Currency {
  KRW = 'KRW',
  USD = 'USD',
  JPY = 'JPY',
}

export enum Status {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
}

export enum ItemType {
  PLACE = 'PLACE',
  EVENT = 'EVENT',
  BOOKING = 'BOOKING',
  DELIVERY = 'DELIVERY',
  SERVICE = 'SERVICE',
}

export enum Paymethod {
  CASH = 'CASH',
  CARD = 'CARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
}

export enum BankCode {
  BOK = '001',
  KDB = '002',
  IBK = '003',
  KB = '004',
  SUHYUP = '007',
  NONGHYUP = '011',
  WOORI = '020',
  STANDARD_CHARTERED = '023',
  CITY = '027',
  DAEGU = '031',
  BUSAN = '032',
  KN_BANK = '039',
  GUANGJU = '034',
  JEJU = '035',
  HANA = '081',
  SHINHAN = '088',
  KAKAO = '090',
  POST = '071',
}
